# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\QtProjects\pyqt_demo\wanlihong2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.case_table = QtWidgets.QTableWidget(self.centralwidget)
        self.case_table.setGeometry(QtCore.QRect(20, 20, 760, 400))
        self.case_table.setObjectName("case_table")
        self.case_table.setColumnCount(0)
        self.case_table.setRowCount(0)
        self.button_new_case = QtWidgets.QPushButton(self.centralwidget)
        self.button_new_case.setGeometry(QtCore.QRect(20, 450, 120, 40))
        self.button_new_case.setObjectName("button_new_case")
        self.button_import_cases = QtWidgets.QPushButton(self.centralwidget)
        self.button_import_cases.setGeometry(QtCore.QRect(160, 450, 120, 40))
        self.button_import_cases.setObjectName("button_import_cases")
        self.button_delete_cases = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete_cases.setGeometry(QtCore.QRect(300, 450, 120, 40))
        self.button_delete_cases.setObjectName("button_delete_cases")
        self.button_save_cases = QtWidgets.QPushButton(self.centralwidget)
        self.button_save_cases.setGeometry(QtCore.QRect(440, 450, 120, 40))
        self.button_save_cases.setObjectName("button_save_cases")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Case Management"))
        self.button_new_case.setText(_translate("MainWindow", "New Case"))
        self.button_import_cases.setText(_translate("MainWindow", "Import Cases"))
        self.button_delete_cases.setText(_translate("MainWindow", "Delete Cases"))
        self.button_save_cases.setText(_translate("MainWindow", "Save Cases"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
