# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\QtProjects\pyqt_demo\wanlihong1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_image1 = QtWidgets.QLabel(self.centralwidget)
        self.label_image1.setGeometry(QtCore.QRect(50, 50, 300, 200))
        self.label_image1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image1.setObjectName("label_image1")
        self.label_image2 = QtWidgets.QLabel(self.centralwidget)
        self.label_image2.setGeometry(QtCore.QRect(450, 50, 300, 200))
        self.label_image2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image2.setObjectName("label_image2")
        self.button_load_image1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_load_image1.setGeometry(QtCore.QRect(50, 270, 300, 30))
        self.button_load_image1.setObjectName("button_load_image1")
        self.button_load_image2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_load_image2.setGeometry(QtCore.QRect(450, 270, 300, 30))
        self.button_load_image2.setObjectName("button_load_image2")
        self.button_analyze = QtWidgets.QPushButton(self.centralwidget)
        self.button_analyze.setGeometry(QtCore.QRect(250, 320, 300, 30))
        self.button_analyze.setObjectName("button_analyze")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(250, 370, 300, 50))
        self.label_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_result.setObjectName("label_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Portrait Identity Analysis"))
        self.label_image1.setText(_translate("MainWindow", "Image 1"))
        self.label_image2.setText(_translate("MainWindow", "Image 2"))
        self.button_load_image1.setText(_translate("MainWindow", "Load Image 1"))
        self.button_load_image2.setText(_translate("MainWindow", "Load Image 2"))
        self.button_analyze.setText(_translate("MainWindow", "Analyze Similarity"))
        self.label_result.setText(_translate("MainWindow", "Result: N/A"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
