# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\WinProjects\pyqt_demo\wanlihong8.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.image_label_1.setGeometry(QtCore.QRect(10, 10, 370, 200))
        self.image_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label_1.setObjectName("image_label_1")
        self.image_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.image_label_2.setGeometry(QtCore.QRect(400, 10, 370, 200))
        self.image_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label_2.setObjectName("image_label_2")
        self.button_load_image_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_load_image_1.setGeometry(QtCore.QRect(10, 220, 120, 30))
        self.button_load_image_1.setObjectName("button_load_image_1")
        self.button_load_image_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_load_image_2.setGeometry(QtCore.QRect(140, 220, 120, 30))
        self.button_load_image_2.setObjectName("button_load_image_2")
        self.button_perspective_auto = QtWidgets.QPushButton(self.centralwidget)
        self.button_perspective_auto.setGeometry(QtCore.QRect(270, 220, 120, 30))
        self.button_perspective_auto.setObjectName("button_perspective_auto")
        self.button_perspective_manual = QtWidgets.QPushButton(self.centralwidget)
        self.button_perspective_manual.setGeometry(QtCore.QRect(400, 220, 120, 30))
        self.button_perspective_manual.setObjectName("button_perspective_manual")
        self.button_clear_points = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear_points.setGeometry(QtCore.QRect(530, 220, 120, 30))
        self.button_clear_points.setObjectName("button_clear_points")
        self.log_window = QtWidgets.QTextEdit(self.centralwidget)
        self.log_window.setGeometry(QtCore.QRect(10, 270, 770, 200))
        self.log_window.setObjectName("log_window")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Perspective Alignment"))
        self.image_label_1.setText(_translate("MainWindow", "Image 1"))
        self.image_label_2.setText(_translate("MainWindow", "Image 2"))
        self.button_load_image_1.setText(_translate("MainWindow", "Load Image 1"))
        self.button_load_image_2.setText(_translate("MainWindow", "Load Image 2"))
        self.button_perspective_auto.setText(_translate("MainWindow", "Auto Perspective"))
        self.button_perspective_manual.setText(_translate("MainWindow", "Manual Perspective"))
        self.button_clear_points.setText(_translate("MainWindow", "Clear Points"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
