# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\WinProjects\pyqt_demo\wanlihong9.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.image_label_1.setGeometry(QtCore.QRect(10, 10, 370, 200))
        self.image_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label_1.setObjectName("image_label_1")
        self.image_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.image_label_2.setGeometry(QtCore.QRect(400, 10, 370, 200))
        self.image_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label_2.setObjectName("image_label_2")
        self.button_load_image_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_load_image_1.setGeometry(QtCore.QRect(10, 220, 120, 30))
        self.button_load_image_1.setObjectName("button_load_image_1")
        self.button_load_image_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_load_image_2.setGeometry(QtCore.QRect(140, 220, 120, 30))
        self.button_load_image_2.setObjectName("button_load_image_2")
        self.button_coarse_align = QtWidgets.QPushButton(self.centralwidget)
        self.button_coarse_align.setGeometry(QtCore.QRect(270, 220, 120, 30))
        self.button_coarse_align.setObjectName("button_coarse_align")
        self.button_enable_fine_tune = QtWidgets.QPushButton(self.centralwidget)
        self.button_enable_fine_tune.setGeometry(QtCore.QRect(400, 220, 120, 30))
        self.button_enable_fine_tune.setObjectName("button_enable_fine_tune")
        self.slider_translate_x = QtWidgets.QSlider(self.centralwidget)
        self.slider_translate_x.setGeometry(QtCore.QRect(10, 270, 300, 20))
        self.slider_translate_x.setOrientation(QtCore.Qt.Horizontal)
        self.slider_translate_x.setObjectName("slider_translate_x")
        self.slider_translate_y = QtWidgets.QSlider(self.centralwidget)
        self.slider_translate_y.setGeometry(QtCore.QRect(10, 300, 300, 20))
        self.slider_translate_y.setOrientation(QtCore.Qt.Horizontal)
        self.slider_translate_y.setObjectName("slider_translate_y")
        self.slider_rotate = QtWidgets.QSlider(self.centralwidget)
        self.slider_rotate.setGeometry(QtCore.QRect(10, 330, 300, 20))
        self.slider_rotate.setOrientation(QtCore.Qt.Horizontal)
        self.slider_rotate.setObjectName("slider_rotate")
        self.slider_scale = QtWidgets.QSlider(self.centralwidget)
        self.slider_scale.setGeometry(QtCore.QRect(10, 360, 300, 20))
        self.slider_scale.setOrientation(QtCore.Qt.Horizontal)
        self.slider_scale.setObjectName("slider_scale")
        self.log_window = QtWidgets.QTextEdit(self.centralwidget)
        self.log_window.setGeometry(QtCore.QRect(10, 400, 770, 200))
        self.log_window.setObjectName("log_window")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fine Alignment"))
        self.image_label_1.setText(_translate("MainWindow", "Image 1"))
        self.image_label_2.setText(_translate("MainWindow", "Image 2"))
        self.button_load_image_1.setText(_translate("MainWindow", "Load Image 1"))
        self.button_load_image_2.setText(_translate("MainWindow", "Load Image 2"))
        self.button_coarse_align.setText(_translate("MainWindow", "Coarse Align"))
        self.button_enable_fine_tune.setText(_translate("MainWindow", "Enable Fine Tune"))
        self.slider_translate_x.setToolTip(_translate("MainWindow", "Translate X"))
        self.slider_translate_y.setToolTip(_translate("MainWindow", "Translate Y"))
        self.slider_rotate.setToolTip(_translate("MainWindow", "Rotate"))
        self.slider_scale.setToolTip(_translate("MainWindow", "Scale"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
