# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\WinProjects\pyqt_demo\wanlihong4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.file_table = QtWidgets.QTableWidget(self.centralwidget)
        self.file_table.setGeometry(QtCore.QRect(20, 20, 500, 400))
        self.file_table.setObjectName("file_table")
        self.file_table.setColumnCount(0)
        self.file_table.setRowCount(0)
        self.file_preview = QtWidgets.QLabel(self.centralwidget)
        self.file_preview.setGeometry(QtCore.QRect(540, 20, 240, 180))
        self.file_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.file_preview.setObjectName("file_preview")
        self.button_load_file = QtWidgets.QPushButton(self.centralwidget)
        self.button_load_file.setGeometry(QtCore.QRect(20, 450, 120, 40))
        self.button_load_file.setObjectName("button_load_file")
        self.button_delete_file = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete_file.setGeometry(QtCore.QRect(160, 450, 120, 40))
        self.button_delete_file.setObjectName("button_delete_file")
        self.button_reload_file = QtWidgets.QPushButton(self.centralwidget)
        self.button_reload_file.setGeometry(QtCore.QRect(300, 450, 120, 40))
        self.button_reload_file.setObjectName("button_reload_file")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "File Information Viewer"))
        self.file_preview.setText(_translate("MainWindow", "Preview Area"))
        self.button_load_file.setText(_translate("MainWindow", "Load File"))
        self.button_delete_file.setText(_translate("MainWindow", "Delete File"))
        self.button_reload_file.setText(_translate("MainWindow", "Reload File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
