# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\WinProjects\pyqt_demo\wanlihong12.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setGeometry(QtCore.QRect(10, 10, 770, 400))
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.button_load_image = QtWidgets.QPushButton(self.centralwidget)
        self.button_load_image.setGeometry(QtCore.QRect(10, 420, 120, 30))
        self.button_load_image.setObjectName("button_load_image")
        self.button_draw_arrow = QtWidgets.QPushButton(self.centralwidget)
        self.button_draw_arrow.setGeometry(QtCore.QRect(140, 420, 120, 30))
        self.button_draw_arrow.setObjectName("button_draw_arrow")
        self.button_undo = QtWidgets.QPushButton(self.centralwidget)
        self.button_undo.setGeometry(QtCore.QRect(270, 420, 120, 30))
        self.button_undo.setObjectName("button_undo")
        self.button_save_screenshot = QtWidgets.QPushButton(self.centralwidget)
        self.button_save_screenshot.setGeometry(QtCore.QRect(400, 420, 120, 30))
        self.button_save_screenshot.setObjectName("button_save_screenshot")
        self.log_window = QtWidgets.QTextEdit(self.centralwidget)
        self.log_window.setGeometry(QtCore.QRect(10, 460, 770, 200))
        self.log_window.setObjectName("log_window")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Annotation with Arrows"))
        self.image_label.setText(_translate("MainWindow", "Image"))
        self.button_load_image.setText(_translate("MainWindow", "Load Image"))
        self.button_draw_arrow.setText(_translate("MainWindow", "Draw Arrow"))
        self.button_undo.setText(_translate("MainWindow", "Undo"))
        self.button_save_screenshot.setText(_translate("MainWindow", "Save Screenshot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
