# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\WinProjects\pyqt_demo\wanlihong13.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_load_image_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_load_image_1.setGeometry(QtCore.QRect(30, 420, 140, 30))
        self.button_load_image_1.setObjectName("button_load_image_1")
        self.button_load_image_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_load_image_2.setGeometry(QtCore.QRect(530, 420, 140, 30))
        self.button_load_image_2.setObjectName("button_load_image_2")
        self.button_select_points = QtWidgets.QPushButton(self.centralwidget)
        self.button_select_points.setGeometry(QtCore.QRect(30, 460, 171, 30))
        self.button_select_points.setObjectName("button_select_points")
        self.button_calculate_results = QtWidgets.QPushButton(self.centralwidget)
        self.button_calculate_results.setGeometry(QtCore.QRect(530, 460, 140, 30))
        self.button_calculate_results.setObjectName("button_calculate_results")
        self.label_image_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_image_1.setGeometry(QtCore.QRect(30, 50, 280, 360))
        self.label_image_1.setObjectName("label_image_1")
        self.label_image_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_image_2.setGeometry(QtCore.QRect(390, 50, 280, 360))
        self.label_image_2.setObjectName("label_image_2")
        self.textEdit_results = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_results.setGeometry(QtCore.QRect(30, 380, 640, 30))
        self.textEdit_results.setObjectName("textEdit_results")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Measurement Tool"))
        self.button_load_image_1.setText(_translate("MainWindow", "Load Image 1"))
        self.button_load_image_2.setText(_translate("MainWindow", "Load Image 2"))
        self.button_select_points.setText(_translate("MainWindow", "Select Measurement Points"))
        self.button_calculate_results.setText(_translate("MainWindow", "Calculate Results"))
        self.label_image_1.setText(_translate("MainWindow", "Image 1"))
        self.label_image_2.setText(_translate("MainWindow", "Image 2"))
        self.textEdit_results.setPlainText(_translate("MainWindow", "Results will be displayed here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
