# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\WinProjects\pyqt_demo\wanlihong11.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.image_label_1.setGeometry(QtCore.QRect(10, 10, 370, 300))
        self.image_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label_1.setObjectName("image_label_1")
        self.image_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.image_label_2.setGeometry(QtCore.QRect(400, 10, 370, 300))
        self.image_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label_2.setObjectName("image_label_2")
        self.button_load_image_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_load_image_1.setGeometry(QtCore.QRect(10, 320, 120, 30))
        self.button_load_image_1.setObjectName("button_load_image_1")
        self.button_load_image_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_load_image_2.setGeometry(QtCore.QRect(140, 320, 120, 30))
        self.button_load_image_2.setObjectName("button_load_image_2")
        self.button_start_comparison = QtWidgets.QPushButton(self.centralwidget)
        self.button_start_comparison.setGeometry(QtCore.QRect(270, 320, 120, 30))
        self.button_start_comparison.setObjectName("button_start_comparison")
        self.result_display = QtWidgets.QTextEdit(self.centralwidget)
        self.result_display.setGeometry(QtCore.QRect(10, 360, 770, 280))
        self.result_display.setReadOnly(True)
        self.result_display.setObjectName("result_display")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Facial Proportion Comparison"))
        self.image_label_1.setText(_translate("MainWindow", "Image 1"))
        self.image_label_2.setText(_translate("MainWindow", "Image 2"))
        self.button_load_image_1.setText(_translate("MainWindow", "Load Image 1"))
        self.button_load_image_2.setText(_translate("MainWindow", "Load Image 2"))
        self.button_start_comparison.setText(_translate("MainWindow", "Start Comparison"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
