# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\QtProjects\pyqt_demo\wanlihong.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1180, 700))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_case_management = QtWidgets.QWidget()
        self.tab_case_management.setObjectName("tab_case_management")
        self.table_case_files = QtWidgets.QTableWidget(self.tab_case_management)
        self.table_case_files.setGeometry(QtCore.QRect(10, 10, 1150, 600))
        self.table_case_files.setObjectName("table_case_files")
        self.table_case_files.setColumnCount(0)
        self.table_case_files.setRowCount(0)
        self.button_new_case = QtWidgets.QPushButton(self.tab_case_management)
        self.button_new_case.setGeometry(QtCore.QRect(10, 620, 150, 30))
        self.button_new_case.setObjectName("button_new_case")
        self.button_import_case = QtWidgets.QPushButton(self.tab_case_management)
        self.button_import_case.setGeometry(QtCore.QRect(170, 620, 150, 30))
        self.button_import_case.setObjectName("button_import_case")
        self.button_modify_case = QtWidgets.QPushButton(self.tab_case_management)
        self.button_modify_case.setGeometry(QtCore.QRect(330, 620, 150, 30))
        self.button_modify_case.setObjectName("button_modify_case")
        self.button_delete_case = QtWidgets.QPushButton(self.tab_case_management)
        self.button_delete_case.setGeometry(QtCore.QRect(490, 620, 150, 30))
        self.button_delete_case.setObjectName("button_delete_case")
        self.tabWidget.addTab(self.tab_case_management, "")
        self.tab_preprocessing = QtWidgets.QWidget()
        self.tab_preprocessing.setObjectName("tab_preprocessing")
        self.label_original_image = QtWidgets.QLabel(self.tab_preprocessing)
        self.label_original_image.setGeometry(QtCore.QRect(10, 10, 570, 320))
        self.label_original_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_original_image.setObjectName("label_original_image")
        self.label_processed_image = QtWidgets.QLabel(self.tab_preprocessing)
        self.label_processed_image.setGeometry(QtCore.QRect(600, 10, 570, 320))
        self.label_processed_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_processed_image.setObjectName("label_processed_image")
        self.combo_preprocessing_method = QtWidgets.QComboBox(self.tab_preprocessing)
        self.combo_preprocessing_method.setGeometry(QtCore.QRect(10, 350, 300, 30))
        self.combo_preprocessing_method.setObjectName("combo_preprocessing_method")
        self.button_apply_preprocessing = QtWidgets.QPushButton(self.tab_preprocessing)
        self.button_apply_preprocessing.setGeometry(QtCore.QRect(330, 350, 150, 30))
        self.button_apply_preprocessing.setObjectName("button_apply_preprocessing")
        self.button_restore_image = QtWidgets.QPushButton(self.tab_preprocessing)
        self.button_restore_image.setGeometry(QtCore.QRect(490, 350, 150, 30))
        self.button_restore_image.setObjectName("button_restore_image")
        self.tabWidget.addTab(self.tab_preprocessing, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuFile = QtWidgets.QAction(MainWindow)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QAction(MainWindow)
        self.menuHelp.setObjectName("menuHelp")
        self.menubar.addAction(self.menuFile)
        self.menubar.addAction(self.menuHelp)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Portrait Analysis System"))
        self.button_new_case.setText(_translate("MainWindow", "New Case"))
        self.button_import_case.setText(_translate("MainWindow", "Import Case"))
        self.button_modify_case.setText(_translate("MainWindow", "Modify Case"))
        self.button_delete_case.setText(_translate("MainWindow", "Delete Case"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_case_management), _translate("MainWindow", "Case Management"))
        self.label_original_image.setText(_translate("MainWindow", "Original Image"))
        self.label_processed_image.setText(_translate("MainWindow", "Processed Image"))
        self.combo_preprocessing_method.setCurrentText(_translate("MainWindow", "Select Preprocessing Method"))
        self.button_apply_preprocessing.setText(_translate("MainWindow", "Apply"))
        self.button_restore_image.setText(_translate("MainWindow", "Restore Original"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_preprocessing), _translate("MainWindow", "Preprocessing"))
        self.menuFile.setText(_translate("MainWindow", "File"))
        self.menuHelp.setText(_translate("MainWindow", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
