# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\WinProjects\pyqt_demo\wanlihong14.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_load_image = QtWidgets.QPushButton(self.centralwidget)
        self.button_load_image.setGeometry(QtCore.QRect(50, 510, 200, 30))
        self.button_load_image.setObjectName("button_load_image")
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(50, 50, 300, 400))
        self.label_image.setObjectName("label_image")
        self.slider_scale = QtWidgets.QSlider(self.centralwidget)
        self.slider_scale.setGeometry(QtCore.QRect(400, 510, 200, 30))
        self.slider_scale.setOrientation(QtCore.Qt.Horizontal)
        self.slider_scale.setMinimum(1)
        self.slider_scale.setMaximum(200)
        self.slider_scale.setProperty("value", 100)
        self.slider_scale.setObjectName("slider_scale")
        self.button_adjust_point = QtWidgets.QPushButton(self.centralwidget)
        self.button_adjust_point.setGeometry(QtCore.QRect(650, 510, 100, 30))
        self.button_adjust_point.setObjectName("button_adjust_point")
        self.textEdit_results = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_results.setGeometry(QtCore.QRect(50, 460, 700, 40))
        self.textEdit_results.setObjectName("textEdit_results")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Scaling and Point Adjustment"))
        self.button_load_image.setText(_translate("MainWindow", "Load Image"))
        self.label_image.setText(_translate("MainWindow", "Image"))
        self.button_adjust_point.setText(_translate("MainWindow", "Adjust Point"))
        self.textEdit_results.setText(_translate("MainWindow", "Results will be displayed here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
