# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\WinProjects\pyqt_demo\wanlihong28.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textedit_commission = QtWidgets.QTextEdit(self.centralwidget)
        self.textedit_commission.setGeometry(QtCore.QRect(50, 10, 700, 100))
        self.textedit_commission.setObjectName("textedit_commission")
        self.button_upload_image1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_upload_image1.setGeometry(QtCore.QRect(50, 120, 150, 30))
        self.button_upload_image1.setObjectName("button_upload_image1")
        self.button_upload_image2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_upload_image2.setGeometry(QtCore.QRect(250, 120, 150, 30))
        self.button_upload_image2.setObjectName("button_upload_image2")
        self.label_image1 = QtWidgets.QLabel(self.centralwidget)
        self.label_image1.setGeometry(QtCore.QRect(50, 160, 300, 400))
        self.label_image1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image1.setObjectName("label_image1")
        self.label_image2 = QtWidgets.QLabel(self.centralwidget)
        self.label_image2.setGeometry(QtCore.QRect(400, 160, 300, 400))
        self.label_image2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image2.setObjectName("label_image2")
        self.button_save_report = QtWidgets.QPushButton(self.centralwidget)
        self.button_save_report.setGeometry(QtCore.QRect(50, 580, 150, 30))
        self.button_save_report.setObjectName("button_save_report")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "鉴定文书生成工具"))
        self.textedit_commission.setPlaceholderText(_translate("MainWindow", "Enter Commission Details..."))
        self.button_upload_image1.setText(_translate("MainWindow", "Upload Image 1"))
        self.button_upload_image2.setText(_translate("MainWindow", "Upload Image 2"))
        self.label_image1.setText(_translate("MainWindow", "Image 1"))
        self.label_image2.setText(_translate("MainWindow", "Image 2"))
        self.button_save_report.setText(_translate("MainWindow", "Save Report"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
