# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\WinProjects\pyqt_demo\wanlihong3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.case_list = QtWidgets.QListWidget(self.centralwidget)
        self.case_list.setGeometry(QtCore.QRect(10, 10, 180, 580))
        self.case_list.setObjectName("case_list")
        self.material_table = QtWidgets.QTableWidget(self.centralwidget)
        self.material_table.setGeometry(QtCore.QRect(200, 10, 680, 150))
        self.material_table.setObjectName("material_table")
        self.material_table.setColumnCount(0)
        self.material_table.setRowCount(0)
        self.artifact_table = QtWidgets.QTableWidget(self.centralwidget)
        self.artifact_table.setGeometry(QtCore.QRect(200, 170, 680, 150))
        self.artifact_table.setObjectName("artifact_table")
        self.artifact_table.setColumnCount(0)
        self.artifact_table.setRowCount(0)
        self.log_window = QtWidgets.QTextEdit(self.centralwidget)
        self.log_window.setGeometry(QtCore.QRect(200, 330, 680, 150))
        self.log_window.setObjectName("log_window")
        self.button_add_material = QtWidgets.QPushButton(self.centralwidget)
        self.button_add_material.setGeometry(QtCore.QRect(200, 500, 120, 40))
        self.button_add_material.setObjectName("button_add_material")
        self.button_delete_material = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete_material.setGeometry(QtCore.QRect(340, 500, 120, 40))
        self.button_delete_material.setObjectName("button_delete_material")
        self.button_view_material = QtWidgets.QPushButton(self.centralwidget)
        self.button_view_material.setGeometry(QtCore.QRect(480, 500, 120, 40))
        self.button_view_material.setObjectName("button_view_material")
        self.button_add_artifact = QtWidgets.QPushButton(self.centralwidget)
        self.button_add_artifact.setGeometry(QtCore.QRect(620, 500, 120, 40))
        self.button_add_artifact.setObjectName("button_add_artifact")
        self.button_delete_artifact = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete_artifact.setGeometry(QtCore.QRect(760, 500, 120, 40))
        self.button_delete_artifact.setObjectName("button_delete_artifact")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Case Dossier Management"))
        self.button_add_material.setText(_translate("MainWindow", "Add Material"))
        self.button_delete_material.setText(_translate("MainWindow", "Delete Material"))
        self.button_view_material.setText(_translate("MainWindow", "View Material"))
        self.button_add_artifact.setText(_translate("MainWindow", "Add Artifact"))
        self.button_delete_artifact.setText(_translate("MainWindow", "Delete Artifact"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
