# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\WinProjects\pyqt_demo\wanlihong15.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_upload_image = QtWidgets.QPushButton(self.centralwidget)
        self.button_upload_image.setGeometry(QtCore.QRect(50, 10, 150, 30))
        self.button_upload_image.setObjectName("button_upload_image")
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(50, 50, 700, 400))
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image.setObjectName("label_image")
        self.button_undo = QtWidgets.QPushButton(self.centralwidget)
        self.button_undo.setGeometry(QtCore.QRect(50, 510, 100, 30))
        self.button_undo.setObjectName("button_undo")
        self.button_reset = QtWidgets.QPushButton(self.centralwidget)
        self.button_reset.setGeometry(QtCore.QRect(160, 510, 100, 30))
        self.button_reset.setObjectName("button_reset")
        self.button_modify = QtWidgets.QPushButton(self.centralwidget)
        self.button_modify.setGeometry(QtCore.QRect(270, 510, 100, 30))
        self.button_modify.setObjectName("button_modify")
        self.button_delete = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete.setGeometry(QtCore.QRect(380, 510, 100, 30))
        self.button_delete.setObjectName("button_delete")
        self.button_screenshot = QtWidgets.QPushButton(self.centralwidget)
        self.button_screenshot.setGeometry(QtCore.QRect(490, 510, 100, 30))
        self.button_screenshot.setObjectName("button_screenshot")
        self.button_generate_table = QtWidgets.QPushButton(self.centralwidget)
        self.button_generate_table.setGeometry(QtCore.QRect(600, 510, 150, 30))
        self.button_generate_table.setObjectName("button_generate_table")
        self.textEdit_results = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_results.setGeometry(QtCore.QRect(50, 460, 700, 40))
        self.textEdit_results.setReadOnly(True)
        self.textEdit_results.setObjectName("textEdit_results")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Measurement"))
        self.button_upload_image.setText(_translate("MainWindow", "Upload Image"))
        self.label_image.setText(_translate("MainWindow", "Image Display"))
        self.button_undo.setText(_translate("MainWindow", "Undo"))
        self.button_reset.setText(_translate("MainWindow", "Reset"))
        self.button_modify.setText(_translate("MainWindow", "Modify"))
        self.button_delete.setText(_translate("MainWindow", "Delete"))
        self.button_screenshot.setText(_translate("MainWindow", "Screenshot"))
        self.button_generate_table.setText(_translate("MainWindow", "Generate Table"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
