# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\WinProjects\pyqt_demo\wanlihong30.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setGeometry(QtCore.QRect(10, 10, 880, 680))
        self.tab_widget.setObjectName("tab_widget")
        self.tab_case_info = QtWidgets.QWidget()
        self.tab_case_info.setObjectName("tab_case_info")
        self.textedit_case_info = QtWidgets.QTextEdit(self.tab_case_info)
        self.textedit_case_info.setGeometry(QtCore.QRect(10, 10, 850, 630))
        self.textedit_case_info.setReadOnly(True)
        self.textedit_case_info.setObjectName("textedit_case_info")
        self.tab_widget.addTab(self.tab_case_info, "")
        self.tab_materials = QtWidgets.QWidget()
        self.tab_materials.setObjectName("tab_materials")
        self.label_image1 = QtWidgets.QLabel(self.tab_materials)
        self.label_image1.setGeometry(QtCore.QRect(50, 50, 300, 400))
        self.label_image1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image1.setObjectName("label_image1")
        self.label_image2 = QtWidgets.QLabel(self.tab_materials)
        self.label_image2.setGeometry(QtCore.QRect(500, 50, 300, 400))
        self.label_image2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image2.setObjectName("label_image2")
        self.tab_widget.addTab(self.tab_materials, "")
        self.tab_preprocessing = QtWidgets.QWidget()
        self.tab_preprocessing.setObjectName("tab_preprocessing")
        self.textedit_preprocessing_results = QtWidgets.QTextEdit(self.tab_preprocessing)
        self.textedit_preprocessing_results.setGeometry(QtCore.QRect(10, 10, 850, 630))
        self.textedit_preprocessing_results.setReadOnly(True)
        self.textedit_preprocessing_results.setObjectName("textedit_preprocessing_results")
        self.tab_widget.addTab(self.tab_preprocessing, "")
        self.tab_feature_comparison = QtWidgets.QWidget()
        self.tab_feature_comparison.setObjectName("tab_feature_comparison")
        self.textedit_feature_comparison = QtWidgets.QTextEdit(self.tab_feature_comparison)
        self.textedit_feature_comparison.setGeometry(QtCore.QRect(10, 10, 850, 630))
        self.textedit_feature_comparison.setReadOnly(True)
        self.textedit_feature_comparison.setObjectName("textedit_feature_comparison")
        self.tab_widget.addTab(self.tab_feature_comparison, "")
        self.tab_measurement_comparison = QtWidgets.QWidget()
        self.tab_measurement_comparison.setObjectName("tab_measurement_comparison")
        self.textedit_measurement_comparison = QtWidgets.QTextEdit(self.tab_measurement_comparison)
        self.textedit_measurement_comparison.setGeometry(QtCore.QRect(10, 10, 850, 630))
        self.textedit_measurement_comparison.setReadOnly(True)
        self.textedit_measurement_comparison.setObjectName("textedit_measurement_comparison")
        self.tab_widget.addTab(self.tab_measurement_comparison, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "案件卷宗管理工具"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_case_info), _translate("MainWindow", "案件卷宗信息"))
        self.label_image1.setText(_translate("MainWindow", "Image 1"))
        self.label_image2.setText(_translate("MainWindow", "Image 2"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_materials), _translate("MainWindow", "检材和样本"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_preprocessing), _translate("MainWindow", "预处理结果"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_feature_comparison), _translate("MainWindow", "特征比对"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_measurement_comparison), _translate("MainWindow", "测量比对"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
