# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\WinProjects\pyqt_demo\wanlihong16.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_upload_image = QtWidgets.QPushButton(self.centralwidget)
        self.button_upload_image.setGeometry(QtCore.QRect(50, 20, 150, 30))
        self.button_upload_image.setObjectName("button_upload_image")
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(50, 60, 700, 400))
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image.setObjectName("label_image")
        self.button_add_point = QtWidgets.QPushButton(self.centralwidget)
        self.button_add_point.setGeometry(QtCore.QRect(50, 510, 120, 30))
        self.button_add_point.setObjectName("button_add_point")
        self.button_measure_distance = QtWidgets.QPushButton(self.centralwidget)
        self.button_measure_distance.setGeometry(QtCore.QRect(180, 510, 120, 30))
        self.button_measure_distance.setObjectName("button_measure_distance")
        self.button_measure_angle = QtWidgets.QPushButton(self.centralwidget)
        self.button_measure_angle.setGeometry(QtCore.QRect(310, 510, 120, 30))
        self.button_measure_angle.setObjectName("button_measure_angle")
        self.button_measure_ratio = QtWidgets.QPushButton(self.centralwidget)
        self.button_measure_ratio.setGeometry(QtCore.QRect(440, 510, 120, 30))
        self.button_measure_ratio.setObjectName("button_measure_ratio")
        self.button_save_logs = QtWidgets.QPushButton(self.centralwidget)
        self.button_save_logs.setGeometry(QtCore.QRect(570, 510, 120, 30))
        self.button_save_logs.setObjectName("button_save_logs")
        self.textEdit_logs = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_logs.setGeometry(QtCore.QRect(50, 470, 700, 30))
        self.textEdit_logs.setReadOnly(True)
        self.textEdit_logs.setObjectName("textEdit_logs")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Measurement Tool"))
        self.button_upload_image.setText(_translate("MainWindow", "Upload Image"))
        self.label_image.setText(_translate("MainWindow", "Image Display"))
        self.button_add_point.setText(_translate("MainWindow", "Add Endpoint"))
        self.button_measure_distance.setText(_translate("MainWindow", "Measure Distance"))
        self.button_measure_angle.setText(_translate("MainWindow", "Measure Angle"))
        self.button_measure_ratio.setText(_translate("MainWindow", "Measure Ratio"))
        self.button_save_logs.setText(_translate("MainWindow", "Save Logs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
