# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\WinProjects\pyqt_demo\wanlihong6.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.original_image_label = QtWidgets.QLabel(self.centralwidget)
        self.original_image_label.setGeometry(QtCore.QRect(10, 10, 370, 200))
        self.original_image_label.setObjectName("original_image_label")
        self.processed_image_label = QtWidgets.QLabel(self.centralwidget)
        self.processed_image_label.setGeometry(QtCore.QRect(400, 10, 370, 200))
        self.processed_image_label.setObjectName("processed_image_label")
        self.preprocessing_options = QtWidgets.QComboBox(self.centralwidget)
        self.preprocessing_options.setGeometry(QtCore.QRect(10, 230, 150, 30))
        self.preprocessing_options.setObjectName("preprocessing_options")
        self.button_load_image = QtWidgets.QPushButton(self.centralwidget)
        self.button_load_image.setGeometry(QtCore.QRect(10, 440, 120, 30))
        self.button_load_image.setObjectName("button_load_image")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Preprocessing"))
        self.original_image_label.setText(_translate("MainWindow", "Original Image"))
        self.processed_image_label.setText(_translate("MainWindow", "Processed Image"))
        self.button_load_image.setText(_translate("MainWindow", "Load Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
